CREATE TABLE `question` (
  `seq` int NOT NULL AUTO_INCREMENT,
  `crdt` char(8) NOT NULL,
  `time` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `id` varchar(50) NOT NULL,
  `model` varchar(50) NOT NULL COMMENT '사용할 모델의 ID입니다. 모델 목록 API를 사용하여 사용 가능한 모든 모델을 보거나 모델 개요 에서 설명을 볼 수 있습니다',
  `prompt` varchar(4096) NOT NULL COMMENT '질문내용',
  `prompt_255` varchar(255) NOT NULL,
  `suffix` varchar(100) DEFAULT NULL COMMENT '삽입된 텍스트가 완료된 뒤에 오는 접미사.',
  `max_tokens` tinyint DEFAULT NULL COMMENT '완료 시 생성할 최대 토큰 수입니다.',
  `temperature` float DEFAULT NULL,
  `top_p` float DEFAULT NULL,
  `n` int DEFAULT NULL COMMENT '답변건수',
  `stream` char(1) DEFAULT NULL COMMENT '부분 진행 상황을 스트리밍할지 여부입니다.',
  `logprobs` int DEFAULT NULL,
  `echo` char(1) DEFAULT NULL COMMENT '완료와 함께 프롬프트를 되풀이합니다.',
  `stop` tinytext,
  `presence_penalty` float DEFAULT NULL COMMENT '-2.0에서 2.0 사이의 숫자입니다. 양수 값은 지금까지 텍스트에 ',
  `frequency_penalty` float DEFAULT NULL COMMENT '-2.0에서 2.0 사이의 숫자입니다. 양수 값은 지금까지 텍스트의 기존 빈도를 기반으로 새 토큰에 페널티를 주어 모델이 동일한 줄을 그대로 반복할 가능성을 줄입니다.',
  `best_of` int DEFAULT NULL,
  `logit_bias` varchar(100) DEFAULT NULL,
  `user` varchar(50) DEFAULT NULL,
  `views` int DEFAULT NULL,
  PRIMARY KEY (`seq`),
  FULLTEXT KEY `prompt_255` (`prompt_255`)
) ENGINE=InnoDB AUTO_INCREMENT=310 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='질문 테이블' 